name: tourkarbalaa
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.4
  url_launcher: ^5.4.2
  share: ^0.6.3+5
  http: ^0.12.0+3
  cloud_firestore: ^0.13.1




dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/about/background.png
    - assets/images/about/splash.png
    - assets/images/about/ameer.jpg
    - assets/images/about/daleel.jpg
    - assets/images/about/team.jpg
    - assets/images/about/team1.jpg
    - assets/images/about/team2.jpg
    - assets/images/about/logoc4i.png
    - assets/images/about/codeforiraq.png
    - assets/images/hotels/alamda.jpg
    - assets/images/hotels/albaron.jpg
    - assets/images/hotels/alfnar.jpg
    - assets/images/hotels/alhmery.jpg
    - assets/images/hotels/alhyat.jpg
    - assets/images/hotels/almezan.jpg
    - assets/images/hotels/alsjra_altyba.jpg
    - assets/images/hotels/anwar_karbala.jpg
    - assets/images/hotels/brj_karbala.jpg
    - assets/images/hotels/crystal.jpg
    - assets/images/hotels/earth_alnoor.jpg
    - assets/images/hotels/huda_alwaly.jpg
    - assets/images/hotels/jnat_alhussien.jpg
    - assets/images/hotels/olad_alhsn.jpg
    - assets/images/hotels/ryhan_rotana.jpg
    - assets/images/places_den/ahmed_bn_hashem.jpg
    - assets/images/places_den/alatba_albasya.jpg
    - assets/images/places_den/alatba_alhussenya.jpg
    - assets/images/places_den/alhur.jpg
    - assets/images/places_den/alkhider.jpg
    - assets/images/places_den/almkhem_alhusseny.jpg
    - assets/images/places_den/alqtara.jpg
    - assets/images/places_den/alsbaya.jpg
    - assets/images/places_den/altl_alzainby.jpg
    - assets/images/places_den/aoon_bn_abdulah.jpg
    - assets/images/places_den/madina_imam_hussien.jpg
    - assets/images/places_den/madina_seed_ousyaa.jpg
    - assets/images/places_den/mdina_imam_hasn.jpg
    - assets/images/places_den/sahb_alzman.jpg
    - assets/images/places_den/totha.jpg
    - assets/images/places_tourists/razaza.jpg
    - assets/images/places_tourists/alqataraa.jpg
    - assets/images/places_tourists/boabt_iraq.jpg
    - assets/images/places_tourists/gentra_white.jpg
    - assets/images/places_tourists/hsn_alakhider.jpg
    - assets/images/places_tourists/khan_alnakhila.jpg
    - assets/images/places_tourists/khoof_altar.jpg
    - assets/images/places_tourists/knesat_alakhiser.jpg
    - assets/images/places_tourists/kornesh_alhindea.jpg
    - assets/images/places_tourists/mnart_mojda.jpg
    - assets/images/places_tourists/mntga_hy_hussien.jpg
    - assets/images/places_tourists/mntga_wahat_aream.jpg
    - assets/images/places_tourists/noars_karbala.jpg
    - assets/images/places_tourists/noart_amlak.jpg
    - assets/images/places_tourists/sndbad.jpg
    - assets/images/restaurants/eat_and_go.jpg
    - assets/images/restaurants/aldr_alnsrawe.jpg
    - assets/images/restaurants/pitza_house.jpg
    - assets/images/restaurants/zit_and_zater.jpg
    - assets/images/restaurants/shish_sahwrma.jpg
    - assets/images/restaurants/ali_yousef.jpg
    - assets/images/restaurants/kentaky_house.jpg
    - assets/images/restaurants/kokh_djaj.jpg
    - assets/images/restaurants/groub_bet_almsahwe.jpg
    - assets/images/restaurants/algha.jpg
    - assets/images/restaurants/albet_aldmsgy.jpg
    - assets/images/restaurants/alnakheel.jpg
    - assets/images/restaurants/bery_bery.jpg
    - assets/images/restaurants/khan_mandy.jpg
    - assets/images/restaurants/ashtar.jpg
    - assets/images/restaurants/kbab_abo_nabeel.jpg
    - assets/images/restaurants/kbab_habeb.jpg
    - assets/images/restaurants/kbab_mhmd.jpg
    - assets/images/restaurants/kbab_nabeel.jpg
    - assets/images/restaurants/lebnan_green.jpg
    - assets/images/restaurants/alameer.jpg
    - assets/images/restaurants/hadeez.jpg






  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
